export enum Type {
  ALMACEN = 'ALMACEN',
  ALMACENAMIENTO = 'ALMACENAMIENTO',
  APARTAMENTO = 'APARTAMENTO',
  CASASMOVIL = 'CASAS MOVIL',
  DESARROLLOSDETIERRA = 'DESARROLLOS DE TIERRA',
  ECO = 'ECO',
  GARAJESDEESTACIONAMIENTO = 'GARAJES DE ESTACIONAMIENTO',
  GASOLINERA = 'GASOLINERA',
  HOSPITALIDAD = 'HOSPITALIDAD',
  INTSTALACIONESDEJUBILADO = 'INTSTALACIONES DE JUBILADO',
  OFICINAYMEDICO = 'OFICINA Y MEDICO',
  VENTAMINORISTA = 'VENTA MINORISTA',
}
